Repository trajcex/Cineo, pull requests merged in 2024-07, with the labels that each got.

#6 Feat/search movie
  Backend/infrastructure/bin/infrastructure.ts
  Backend/infrastructure/lambda/searchMovie.py
  Backend/infrastructure/lambda/uploadMovie.py
  Backend/infrastructure/lib/cognito-statck.ts
  Backend/infrastructure/lib/infrastructure-stack.ts
Labels: enhancement

#11 Feat/add movies front
  Backend/infrastructure/bin/infrastructure.ts
  Frontend/angular.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/app-routing.module.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/infrastructure/auth/auth.guard.ts
  Frontend/src/app/infrastructure/auth/auth.module.ts
  Frontend/src/app/infrastructure/auth/log-in/log-in.component.html
  Frontend/src/app/infrastructure/material/material.module.ts
  Frontend/src/app/layout/layout.module.ts
  Frontend/src/app/layout/nav-bar/nav-bar.component.css
  Frontend/src/app/layout/nav-bar/nav-bar.component.html
  Frontend/src/app/layout/nav-bar/nav-bar.component.spec.ts
  Frontend/src/app/layout/nav-bar/nav-bar.component.ts
  Frontend/src/app/movie/add-movie/add-movie.component.css
  Frontend/src/app/movie/add-movie/add-movie.component.html
  Frontend/src/app/movie/add-movie/add-movie.component.spec.ts
  Frontend/src/app/movie/add-movie/add-movie.component.ts
  Frontend/src/app/movie/movie.module.ts
  Frontend/src/app/movie/video-upload/video-upload.component.css
  Frontend/src/app/movie/video-upload/video-upload.component.html
  Frontend/src/app/movie/video-upload/video-upload.component.spec.ts
  Frontend/src/app/movie/video-upload/video-upload.component.ts
  Frontend/src/app/movie/view-movie/view-movie.component.css
  Frontend/src/app/movie/view-movie/view-movie.component.html
  Frontend/src/app/movie/view-movie/view-movie.component.spec.ts
  Frontend/src/app/movie/view-movie/view-movie.component.ts
  Frontend/src/app/movies-page/all-movies/all-movies.component.css
  Frontend/src/app/movies-page/all-movies/all-movies.component.html
  Frontend/src/app/movies-page/all-movies/all-movies.component.spec.ts
  Frontend/src/app/movies-page/all-movies/all-movies.component.ts
  Frontend/src/app/movies-page/movies-page.module.ts
  Frontend/src/app/subscriptions/subscriptions.module.ts
  Frontend/src/assets/images/logo-no-background.svg
  Frontend/src/assets/images/upload_video.svg
  Frontend/src/env/env.ts
  Frontend/src/index.html
  Frontend/src/styles.css
Labels: enhancement

#12 Feature/sqs queue
  Backend/infrastructure/bin/infrastructure.ts
  Backend/infrastructure/lambda/auth.js
  Backend/infrastructure/lambda/deleteMovie.py
  Backend/infrastructure/lambda/downloadMovie.py
  Backend/infrastructure/lambda/getMovie.py
  Backend/infrastructure/lambda/getMovieUrl.py
  Backend/infrastructure/lambda/getPostUrl.py
  Backend/infrastructure/lambda/stepFunctionInvoker.py
  Backend/infrastructure/lambda/transcodeContent.py
  Backend/infrastructure/lambda/uploadMovie.py
  Backend/infrastructure/lib/contentTranscoder-stack.ts
  Backend/infrastructure/lib/data-stack.ts
  Backend/infrastructure/lib/infrastructure-stack.ts
Labels: enhancement

#13 Feat: Subscribe and unsubscribe on topic
  Backend/infrastructure/bin/infrastructure.ts
  Backend/infrastructure/lambda/getSubscription.py
  Backend/infrastructure/lambda/messageDispatcher.py
  Backend/infrastructure/lambda/subscribeTopic.py
  Backend/infrastructure/lambda/unsubscribeTopic.py
  Backend/infrastructure/lib/infrastructure-stack.ts
Labels: enhancement

#14 Bugfix/add movie
  Backend/infrastructure/bin/infrastructure.ts
  Backend/infrastructure/lambda/uploadMovie.py
  Frontend/src/app/layout/nav-bar/nav-bar.component.css
  Frontend/src/app/layout/nav-bar/nav-bar.component.html
  Frontend/src/app/movie/add-movie/add-movie.component.css
  Frontend/src/app/movie/add-movie/add-movie.component.html
  Frontend/src/app/movie/add-movie/add-movie.component.ts
  Frontend/src/app/movie/image-upload/image-upload.component.css
  Frontend/src/app/movie/image-upload/image-upload.component.html
  Frontend/src/app/movie/image-upload/image-upload.component.spec.ts
  Frontend/src/app/movie/image-upload/image-upload.component.ts
  Frontend/src/app/movie/movie.module.ts
  Frontend/src/app/movie/video-upload/video-upload.component.ts
  Frontend/src/app/movies-page/all-movies/all-movies.component.css
  Frontend/src/app/movies-page/all-movies/all-movies.component.html
  Frontend/src/app/movies-page/all-movies/all-movies.component.ts
  Frontend/src/app/movies-page/models/movie.model.ts
  Frontend/src/app/movies-page/movies-page.module.ts
  Frontend/src/app/service/lambda.service.ts
  Frontend/src/assets/images/netflix.png
  Frontend/src/assets/images/upload_image.svg
  Frontend/src/env/env.ts
Labels: enhancement

#15 Feature/video preview
  Backend/infrastructure/lambda/auth.js
  Backend/infrastructure/lambda/deleteMovie.py
  Backend/infrastructure/lambda/getMovie.py
  Backend/infrastructure/lambda/getMovieUrl.py
  Backend/infrastructure/lambda/transcodeContent.py
  Backend/infrastructure/lambda/uploadMovie.py
  Backend/infrastructure/lib/infrastructure-stack.ts
  Frontend/src/app/model/movieInfo.ts
  Frontend/src/app/movie/view-movie/view-movie.component.css
  Frontend/src/app/movie/view-movie/view-movie.component.html
  Frontend/src/app/movie/view-movie/view-movie.component.ts
  Frontend/src/app/service/lambda.service.ts
  Frontend/src/env/env.ts
Labels: enhancement

#18 Feat/view movies
  Backend/infrastructure/lambda/auth.js
  Backend/infrastructure/lambda/getAll.py
  Backend/infrastructure/lambda/searchMovie.py
  Backend/infrastructure/lib/infrastructure-stack.ts
  Frontend/src/app/layout/nav-bar/nav-bar.component.css
  Frontend/src/app/movies-page/all-movies/all-movies.component.css
  Frontend/src/app/movies-page/all-movies/all-movies.component.html
  Frontend/src/app/movies-page/all-movies/all-movies.component.ts
  Frontend/src/app/movies-page/models/movie.model.ts
  Frontend/src/app/movies-page/movies-page.module.ts
  Frontend/src/app/service/lambda.service.ts
  Frontend/src/env/env.ts
Labels: enhancement

#19 Update README.md
  README.md
Labels: bug

#20 Update README.md
  README.md
Labels: documentation

#21 Feature/change movie data
  Backend/infrastructure/bin/infrastructure.ts
  Backend/infrastructure/lambda/auth.js
  Backend/infrastructure/lambda/changeMovieData.py
  Backend/infrastructure/lambda/uploadMovie.py
  Backend/infrastructure/lib/infrastructure-stack.ts
  Frontend/src/app/app-routing.module.ts
  Frontend/src/app/movie/change-movie/change-movie.component.css
  Frontend/src/app/movie/change-movie/change-movie.component.html
  Frontend/src/app/movie/change-movie/change-movie.component.spec.ts
  Frontend/src/app/movie/change-movie/change-movie.component.ts
  Frontend/src/app/movie/movie.module.ts
  Frontend/src/app/movie/view-movie/view-movie.component.html
  Frontend/src/app/movie/view-movie/view-movie.component.ts
  Frontend/src/app/movies-page/all-movies/all-movies.component.html
  Frontend/src/app/service/lambda.service.ts
  Frontend/src/env/env.ts
Labels: enhancement

#22 fix: change design of view-movie page
  Frontend/src/app/movie/view-movie/view-movie.component.css
  Frontend/src/app/movie/view-movie/view-movie.component.html
  Frontend/src/app/movies-page/all-movies/all-movies.component.css
  Frontend/src/assets/images/download-icon.svg
Labels: enhancement

#23 Feat/front deploy
  Backend/infrastructure/lib/infrastructure-stack.ts
  Frontend/angular.json
  Frontend/package.json
  Frontend/src/app/movies-page/all-movies/all-movies.component.css
  Frontend/src/env/env.ts
Labels: enhancement

#25 Feature/update thumbnail
  Backend/infrastructure/lambda/auth.js
  Backend/infrastructure/lambda/changeMovieData.py
  Backend/infrastructure/lambda/getThumbnailUrl.py
  Backend/infrastructure/lib/infrastructure-stack.ts
  Frontend/src/app/movie/change-movie/change-movie.component.html
  Frontend/src/app/movie/change-movie/change-movie.component.ts
  Frontend/src/app/movie/movie.module.ts
  Frontend/src/app/movie/update-image/update-image.component.css
  Frontend/src/app/movie/update-image/update-image.component.html
  Frontend/src/app/movie/update-image/update-image.component.spec.ts
  Frontend/src/app/movie/update-image/update-image.component.ts
  Frontend/src/app/service/lambda.service.ts
  Frontend/src/env/env.ts
Labels: enhancement

#27 Bugfix/update image
  Backend/infrastructure/lambda/changeMovieData.py
  Frontend/src/app/movie/change-movie/change-movie.component.html
  Frontend/src/app/movie/change-movie/change-movie.component.ts
Labels: bug

#28 Feature/get movie content url
  Backend/infrastructure/lambda/auth.js
  Backend/infrastructure/lambda/calculateFeed.py
  Backend/infrastructure/lambda/calculateFeedForMovie.py
  Backend/infrastructure/lambda/changeMovieData.py
  Backend/infrastructure/lambda/getMovieContentUrl.py
  Backend/infrastructure/lambda/getPersonalFeed.py
  Backend/infrastructure/lambda/post-confirmation.py
  Backend/infrastructure/lambda/uploadMovie.py
  Backend/infrastructure/lib/infrastructure-stack.ts
  Frontend/src/app/app-routing.module.ts
  Frontend/src/app/layout/nav-bar/nav-bar.component.html
  Frontend/src/app/movie/change-movie/change-movie.component.html
  Frontend/src/app/movie/view-movie/view-movie.component.html
  Frontend/src/app/movie/view-movie/view-movie.component.ts
  Frontend/src/app/movies-page/all-movies/all-movies.component.css
  Frontend/src/app/service/lambda.service.ts
  Frontend/src/env/env.ts
Labels: enhancement

#29 Update README.md
  README.md
Labels: documentation
